#!/bin/sh

for t in 01 02 03 04 05 06 07 08 09 10 11
do
	echo === Test $t ===
	sort -n < tests/$t > tests/$t.exp
	./sortIntList < tests/$t > tests/$t.out 2>&1

	if diff -Bb tests/$t.exp tests/$t.out > /dev/null 2>&1
	then
		echo "Passed"
	else
		echo "Failed - check differences between tests/$t.exp and tests/$t.out"
	fi
done